// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/coordinator.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedDb   []byte                 `protobuf:"bytes,1,opt,name=encrypted_db,json=encryptedDb,proto3" json:"encrypted_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetadataResponse) GetEncryptedDb() []byte {
	if x != nil {
		return x.EncryptedDb
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CapacityBytes int64                  `protobuf:"varint,3,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NodeInfo) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type UploadPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardCount    int32                  `protobuf:"varint,1,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPlanRequest) Reset() {
	*x = UploadPlanRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPlanRequest) ProtoMessage() {}

func (x *UploadPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPlanRequest.ProtoReflect.Descriptor instead.
func (*UploadPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *UploadPlanRequest) GetShardCount() int32 {
	if x != nil {
		return x.ShardCount
	}
	return 0
}

type UploadPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   map[int32]string       `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // ShardIndex -> NodeEndpoint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPlanResponse) Reset() {
	*x = UploadPlanResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPlanResponse) ProtoMessage() {}

func (x *UploadPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPlanResponse.ProtoReflect.Descriptor instead.
func (*UploadPlanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *UploadPlanResponse) GetAssignments() map[int32]string {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type DownloadPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPlanRequest) Reset() {
	*x = DownloadPlanRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPlanRequest) ProtoMessage() {}

func (x *DownloadPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPlanRequest.ProtoReflect.Descriptor instead.
func (*DownloadPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadPlanRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DownloadPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     map[int32]string       `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // ShardIndex -> NodeEndpoint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPlanResponse) Reset() {
	*x = DownloadPlanResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPlanResponse) ProtoMessage() {}

func (x *DownloadPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPlanResponse.ProtoReflect.Descriptor instead.
func (*DownloadPlanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadPlanResponse) GetLocations() map[int32]string {
	if x != nil {
		return x.Locations
	}
	return nil
}

type UpdateMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedDb   []byte                 `protobuf:"bytes,1,opt,name=encrypted_db,json=encryptedDb,proto3" json:"encrypted_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataRequest) Reset() {
	*x = UpdateMetadataRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataRequest) ProtoMessage() {}

func (x *UpdateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMetadataRequest) GetEncryptedDb() []byte {
	if x != nil {
		return x.EncryptedDb
	}
	return nil
}

type UpdateMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataResponse) Reset() {
	*x = UpdateMetadataResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataResponse) ProtoMessage() {}

func (x *UpdateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_v1_coordinator_proto protoreflect.FileDescriptor

const file_api_proto_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/v1/coordinator.proto\x12\x02v1\"\x14\n" +
	"\x12GetMetadataRequest\"8\n" +
	"\x13GetMetadataResponse\x12!\n" +
	"\fencrypted_db\x18\x01 \x01(\fR\vencryptedDb\"]\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12%\n" +
	"\x0ecapacity_bytes\x18\x03 \x01(\x03R\rcapacityBytes\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"4\n" +
	"\x11UploadPlanRequest\x12\x1f\n" +
	"\vshard_count\x18\x01 \x01(\x05R\n" +
	"shardCount\"\x9f\x01\n" +
	"\x12UploadPlanResponse\x12I\n" +
	"\vassignments\x18\x01 \x03(\v2'.v1.UploadPlanResponse.AssignmentsEntryR\vassignments\x1a>\n" +
	"\x10AssignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x13DownloadPlanRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x9b\x01\n" +
	"\x14DownloadPlanResponse\x12E\n" +
	"\tlocations\x18\x02 \x03(\v2'.v1.DownloadPlanResponse.LocationsEntryR\tlocations\x1a<\n" +
	"\x0eLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x15UpdateMetadataRequest\x12!\n" +
	"\fencrypted_db\x18\x01 \x01(\fR\vencryptedDb\"2\n" +
	"\x16UpdateMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8a\x03\n" +
	"\vCoordinator\x122\n" +
	"\fRegisterNode\x12\f.v1.NodeInfo\x1a\x14.v1.RegisterResponse\x128\n" +
	"\tHeartbeat\x12\x14.v1.HeartbeatRequest\x1a\x15.v1.HeartbeatResponse\x12>\n" +
	"\rGetUploadPlan\x12\x15.v1.UploadPlanRequest\x1a\x16.v1.UploadPlanResponse\x12D\n" +
	"\x0fGetDownloadPlan\x12\x17.v1.DownloadPlanRequest\x1a\x18.v1.DownloadPlanResponse\x12>\n" +
	"\vGetMetadata\x12\x16.v1.GetMetadataRequest\x1a\x17.v1.GetMetadataResponse\x12G\n" +
	"\x0eUpdateMetadata\x12\x19.v1.UpdateMetadataRequest\x1a\x1a.v1.UpdateMetadataResponseB6Z4github.com/Baba01hacker666/Gocryptvault/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_coordinator_proto_rawDescOnce sync.Once
	file_api_proto_v1_coordinator_proto_rawDescData []byte
)

func file_api_proto_v1_coordinator_proto_rawDescGZIP() []byte {
	file_api_proto_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_coordinator_proto_rawDesc), len(file_api_proto_v1_coordinator_proto_rawDesc)))
	})
	return file_api_proto_v1_coordinator_proto_rawDescData
}

var file_api_proto_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_v1_coordinator_proto_goTypes = []any{
	(*GetMetadataRequest)(nil),     // 0: v1.GetMetadataRequest
	(*GetMetadataResponse)(nil),    // 1: v1.GetMetadataResponse
	(*NodeInfo)(nil),               // 2: v1.NodeInfo
	(*RegisterResponse)(nil),       // 3: v1.RegisterResponse
	(*HeartbeatRequest)(nil),       // 4: v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 5: v1.HeartbeatResponse
	(*UploadPlanRequest)(nil),      // 6: v1.UploadPlanRequest
	(*UploadPlanResponse)(nil),     // 7: v1.UploadPlanResponse
	(*DownloadPlanRequest)(nil),    // 8: v1.DownloadPlanRequest
	(*DownloadPlanResponse)(nil),   // 9: v1.DownloadPlanResponse
	(*UpdateMetadataRequest)(nil),  // 10: v1.UpdateMetadataRequest
	(*UpdateMetadataResponse)(nil), // 11: v1.UpdateMetadataResponse
	nil,                            // 12: v1.UploadPlanResponse.AssignmentsEntry
	nil,                            // 13: v1.DownloadPlanResponse.LocationsEntry
}
var file_api_proto_v1_coordinator_proto_depIdxs = []int32{
	12, // 0: v1.UploadPlanResponse.assignments:type_name -> v1.UploadPlanResponse.AssignmentsEntry
	13, // 1: v1.DownloadPlanResponse.locations:type_name -> v1.DownloadPlanResponse.LocationsEntry
	2,  // 2: v1.Coordinator.RegisterNode:input_type -> v1.NodeInfo
	4,  // 3: v1.Coordinator.Heartbeat:input_type -> v1.HeartbeatRequest
	6,  // 4: v1.Coordinator.GetUploadPlan:input_type -> v1.UploadPlanRequest
	8,  // 5: v1.Coordinator.GetDownloadPlan:input_type -> v1.DownloadPlanRequest
	0,  // 6: v1.Coordinator.GetMetadata:input_type -> v1.GetMetadataRequest
	10, // 7: v1.Coordinator.UpdateMetadata:input_type -> v1.UpdateMetadataRequest
	3,  // 8: v1.Coordinator.RegisterNode:output_type -> v1.RegisterResponse
	5,  // 9: v1.Coordinator.Heartbeat:output_type -> v1.HeartbeatResponse
	7,  // 10: v1.Coordinator.GetUploadPlan:output_type -> v1.UploadPlanResponse
	9,  // 11: v1.Coordinator.GetDownloadPlan:output_type -> v1.DownloadPlanResponse
	1,  // 12: v1.Coordinator.GetMetadata:output_type -> v1.GetMetadataResponse
	11, // 13: v1.Coordinator.UpdateMetadata:output_type -> v1.UpdateMetadataResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_coordinator_proto_init() }
func file_api_proto_v1_coordinator_proto_init() {
	if File_api_proto_v1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_coordinator_proto_rawDesc), len(file_api_proto_v1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_coordinator_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_coordinator_proto_msgTypes,
	}.Build()
	File_api_proto_v1_coordinator_proto = out.File
	file_api_proto_v1_coordinator_proto_goTypes = nil
	file_api_proto_v1_coordinator_proto_depIdxs = nil
}
