// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: api/proto/v1/node.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageNode_PutShard_FullMethodName    = "/v1.StorageNode/PutShard"
	StorageNode_GetShard_FullMethodName    = "/v1.StorageNode/GetShard"
	StorageNode_DeleteShard_FullMethodName = "/v1.StorageNode/DeleteShard"
)

// StorageNodeClient is the client API for StorageNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageNodeClient interface {
	PutShard(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShardChunk, PutResponse], error)
	GetShard(ctx context.Context, in *ShardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardChunk], error)
	DeleteShard(ctx context.Context, in *ShardRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type storageNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageNodeClient(cc grpc.ClientConnInterface) StorageNodeClient {
	return &storageNodeClient{cc}
}

func (c *storageNodeClient) PutShard(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShardChunk, PutResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageNode_ServiceDesc.Streams[0], StorageNode_PutShard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShardChunk, PutResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_PutShardClient = grpc.ClientStreamingClient[ShardChunk, PutResponse]

func (c *storageNodeClient) GetShard(ctx context.Context, in *ShardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageNode_ServiceDesc.Streams[1], StorageNode_GetShard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShardRequest, ShardChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_GetShardClient = grpc.ServerStreamingClient[ShardChunk]

func (c *storageNodeClient) DeleteShard(ctx context.Context, in *ShardRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, StorageNode_DeleteShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageNodeServer is the server API for StorageNode service.
// All implementations must embed UnimplementedStorageNodeServer
// for forward compatibility.
type StorageNodeServer interface {
	PutShard(grpc.ClientStreamingServer[ShardChunk, PutResponse]) error
	GetShard(*ShardRequest, grpc.ServerStreamingServer[ShardChunk]) error
	DeleteShard(context.Context, *ShardRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedStorageNodeServer()
}

// UnimplementedStorageNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageNodeServer struct{}

func (UnimplementedStorageNodeServer) PutShard(grpc.ClientStreamingServer[ShardChunk, PutResponse]) error {
	return status.Error(codes.Unimplemented, "method PutShard not implemented")
}
func (UnimplementedStorageNodeServer) GetShard(*ShardRequest, grpc.ServerStreamingServer[ShardChunk]) error {
	return status.Error(codes.Unimplemented, "method GetShard not implemented")
}
func (UnimplementedStorageNodeServer) DeleteShard(context.Context, *ShardRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShard not implemented")
}
func (UnimplementedStorageNodeServer) mustEmbedUnimplementedStorageNodeServer() {}
func (UnimplementedStorageNodeServer) testEmbeddedByValue()                     {}

// UnsafeStorageNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageNodeServer will
// result in compilation errors.
type UnsafeStorageNodeServer interface {
	mustEmbedUnimplementedStorageNodeServer()
}

func RegisterStorageNodeServer(s grpc.ServiceRegistrar, srv StorageNodeServer) {
	// If the following call panics, it indicates UnimplementedStorageNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageNode_ServiceDesc, srv)
}

func _StorageNode_PutShard_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageNodeServer).PutShard(&grpc.GenericServerStream[ShardChunk, PutResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_PutShardServer = grpc.ClientStreamingServer[ShardChunk, PutResponse]

func _StorageNode_GetShard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageNodeServer).GetShard(m, &grpc.GenericServerStream[ShardRequest, ShardChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_GetShardServer = grpc.ServerStreamingServer[ShardChunk]

func _StorageNode_DeleteShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).DeleteShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_DeleteShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).DeleteShard(ctx, req.(*ShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageNode_ServiceDesc is the grpc.ServiceDesc for StorageNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.StorageNode",
	HandlerType: (*StorageNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteShard",
			Handler:    _StorageNode_DeleteShard_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutShard",
			Handler:       _StorageNode_PutShard_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetShard",
			Handler:       _StorageNode_GetShard_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1/node.proto",
}
