// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/node.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardChunk) Reset() {
	*x = ShardChunk{}
	mi := &file_api_proto_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardChunk) ProtoMessage() {}

func (x *ShardChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardChunk.ProtoReflect.Descriptor instead.
func (*ShardChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *ShardChunk) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_api_proto_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardRequest) Reset() {
	*x = ShardRequest{}
	mi := &file_api_proto_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRequest) ProtoMessage() {}

func (x *ShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRequest.ProtoReflect.Descriptor instead.
func (*ShardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *ShardRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_v1_node_proto protoreflect.FileDescriptor

const file_api_proto_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/node.proto\x12\x02v1\";\n" +
	"\n" +
	"ShardChunk\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"'\n" +
	"\vPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\fShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa1\x01\n" +
	"\vStorageNode\x12-\n" +
	"\bPutShard\x12\x0e.v1.ShardChunk\x1a\x0f.v1.PutResponse(\x01\x12.\n" +
	"\bGetShard\x12\x10.v1.ShardRequest\x1a\x0e.v1.ShardChunk0\x01\x123\n" +
	"\vDeleteShard\x12\x10.v1.ShardRequest\x1a\x12.v1.DeleteResponseB6Z4github.com/Baba01hacker666/Gocryptvault/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_node_proto_rawDescOnce sync.Once
	file_api_proto_v1_node_proto_rawDescData []byte
)

func file_api_proto_v1_node_proto_rawDescGZIP() []byte {
	file_api_proto_v1_node_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_node_proto_rawDesc), len(file_api_proto_v1_node_proto_rawDesc)))
	})
	return file_api_proto_v1_node_proto_rawDescData
}

var file_api_proto_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_node_proto_goTypes = []any{
	(*ShardChunk)(nil),     // 0: v1.ShardChunk
	(*PutResponse)(nil),    // 1: v1.PutResponse
	(*ShardRequest)(nil),   // 2: v1.ShardRequest
	(*DeleteResponse)(nil), // 3: v1.DeleteResponse
}
var file_api_proto_v1_node_proto_depIdxs = []int32{
	0, // 0: v1.StorageNode.PutShard:input_type -> v1.ShardChunk
	2, // 1: v1.StorageNode.GetShard:input_type -> v1.ShardRequest
	2, // 2: v1.StorageNode.DeleteShard:input_type -> v1.ShardRequest
	1, // 3: v1.StorageNode.PutShard:output_type -> v1.PutResponse
	0, // 4: v1.StorageNode.GetShard:output_type -> v1.ShardChunk
	3, // 5: v1.StorageNode.DeleteShard:output_type -> v1.DeleteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_node_proto_init() }
func file_api_proto_v1_node_proto_init() {
	if File_api_proto_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_node_proto_rawDesc), len(file_api_proto_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_node_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_node_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_node_proto_msgTypes,
	}.Build()
	File_api_proto_v1_node_proto = out.File
	file_api_proto_v1_node_proto_goTypes = nil
	file_api_proto_v1_node_proto_depIdxs = nil
}
